name: flutter_facebook_auth_web
description: web support for flutter_facebook_auth
version: 6.1.1
homepage: https://github.com/darwin-morocho/flutter-facebook-auth/tree/master/facebook_auth_web


environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_facebook_auth_platform_interface: ^6.1.0
  web: 1.0.0
  # flutter_facebook_auth_platform_interface:
    # path: ../facebook_auth_platform_interface
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterFacebookAuthPlugin
        fileName: flutter_facebook_auth_web.dart
